spring:
  banner:
  location: classpath:banner/banner.txt

amazon:
  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
  aws:
    accesskey:
    secretkey:
    region: us-east-1

amazonProperties:
  accessKey:
  secretKey:
  bucketName: document-prod-client-api
  region: us-east-1

integration:
  client:
    operation-service: http://prod-environment-operation-service.eba-jdji3cpm.us-east-1.elasticbeanstalk.com/operation