spring:
  banner:
  location: classpath:banner/banner.txt

amazon:
  dynamodb:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
  aws:
    accesskey: AKIAVHSSO2TVPHI5L32F
    secretkey: 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
    region: us-east-1

amazonProperties:
  accessKey: AKIAVHSSO2TVPHI5L32F
  secretKey: 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
  bucketName: document-prod-client-api
  region: us-east-1

integration:
  client:
    operation-service: http://prod-environment-operation-service.eba-jdji3cpm.us-east-1.elasticbeanstalk.com/operation