package br.com.cliente.infra.entity

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey
import java.time.LocalDateTime
import java.util.*

class ClientId(
    @field:DynamoDBAutoGeneratedKey
    @field:DynamoDBHashKey(attributeName = "ClientId")
    var clientId: String? = UUID.randomUUID().toString(),

    @field:DynamoDBRangeKey(attributeName = "CreatedAt")
    var createdAt: String? = LocalDateTime.now().toString()
)