package br.com.cliente.infra.entity

import br.com.cliente.infra.dynamodb.DynamoDBConfig
import br.com.cliente.usecase.model.Client
import com.amazonaws.services.dynamodbv2.datamodeling.*
import org.springframework.data.annotation.Id
import java.time.Instant
import java.time.Instant.now
import java.time.LocalDateTime
import java.util.*

@DynamoDBTable(tableName = "Client")
class ClientDocument(
    @Id
    @field:DynamoDBAutoGeneratedKey
    @field:DynamoDBHashKey(attributeName = "ClientId")
    var id: String = UUID.randomUUID().toString(),

    @field:DynamoDBAttribute(attributeName = "AddressClient")
    var addressClient: AddressClientDocument? = null,

    @field:DynamoDBAttribute(attributeName = "NumberDocument")
    var numberDocument: String = "",

    @field:DynamoDBAttribute(attributeName = "ObservationClient")
    var observationClient: String = "",

    @field:DynamoDBAttribute(attributeName = "AttachDocument")
    var attachDocument: String = "",

    @field:DynamoDBAttribute(attributeName = "CreatedAt")
    @field:DynamoDBTypeConverted(converter = DynamoDBConfig.Companion.LocalDateTimeConverter::class)
    var createdAt: LocalDateTime = LocalDateTime.now()
) {
    constructor(client: Client, attachDocument: String) : this(
        addressClient = AddressClientDocument(
            street = client.address.street,
            number = client.address.number,
            zipCode = client.address.zipCode,
            city = client.address.city,
            state = client.address.state,
            district = client.address.district
        ),
        numberDocument = client.numberDocument,
        observationClient = client.observationClient,
        attachDocument = attachDocument
    )

    constructor(client: ClientDocument, attachDocument: String) : this(
        addressClient = client.addressClient?.let {
            AddressClientDocument(
                street = it.street,
                number = client.addressClient!!.number,
                zipCode = client.addressClient!!.zipCode,
                city = client.addressClient!!.city,
                state = client.addressClient!!.state,
                district = client.addressClient!!.district
            )
        },
        numberDocument = client.numberDocument,
        observationClient = client.observationClient,
        attachDocument = attachDocument
    )
}
